language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install pip --upgrade
    - which python3 && which pip
    - python3 --version && python3 -m pip --version
    - python3 -m pip install -r requirements.txt --upgrade
    - python3 -m pip install -r ci-requirements.txt --upgrade
script:
    - coverage run run_tests.py
    - coverage report
