site_name: zerolib Documentation
repo_url: https://github.com/MuxZeroNet/zerolib

theme:
    name: readthedocs

pages:
    - Home: 'index.md'
    - Reference:
        - 'zerolib.integrity': 'reference/integrity.md'
        - 'zerolib.protocol': 'reference/protocol.md'
